### PR TITLE
Validate field fix

### PR DESCRIPTION
**Pull request by chillu**
Replaces https://github.com/silverstripe/silverstripe-spamprotection/pull/27. Reformatted to PSR-2, and added unit tests.

### CODE REVIEW

**Comment by chillu** [comment]
Need to figure out if the new `composer install` of the optional module dpeendency actually works :)

**Comment by tractorcow** [comment]
Hi @chillu , I've removed EditableFormField::validateField in another PR. https://github.com/silverstripe/silverstripe-userforms/pull/409

The problem is trying to delegate validation to a dataobject, rather than a form field, bypasses too many core SilverStripe API, hence things such as spam protection failing.

I think this fix is fine for userforms 3.x, but could you please review my PR in the context of a 4.x compatible solution?

I think this fix should be merged, but it will only resolve one symptom of a larger problem in userform validation. Unfortunately, it's addressed in a breaking way, hence the necessity for a major version. :dancer:

**Comment by chillu** [comment]
Damn, I knew I should've asked somebody before working on this ;) It's interesting how you can tell the relatively fragile API by looking at how many dependencies need to be mocked to make it work, right? To its credit though, most of that stems from core deficiencies. Let's wait on the outcome of the discussion on your other PR.

**Comment by tractorcow** [comment]
Whenever you throw away the API to add a "custom implementation" things will always go wrong. :D

**Comment by chillu** [comment]
Hey Damian, I've mentioned on the other PR that I don't have enough knowledge of userforms to merge it. I do however think I understand the scope of this pull request, in the 3.x release line. Do you think there's anything blocking the merge of this? Keep in mind that I've really just added tests to the PR @timkung created :)

**Comment by tractorcow** [comment]
I think we'll merge this, and keep mine open for the time being.

**Comment by tractorcow** [comment]
I'm going to rebase my Pr on top of this.

**Pull request merged**
