### PR TITLE
Make use of EditableFormField updateFormField

### PR DESCRIPTION
**Pull request by 3Dgoo**
This fixes issue #61

### CODE REVIEW

**Comment by 3Dgoo** [comment]
Hello. Is there anything I can do to get this PR looked at?

**Review by robbieaverill — APPROVED** [review]
I can't merge, but looks to me

**Comment by emteknetnz** [comment]
Yep this looks good.  This PR makes it consistent with what other EditableFormFields do e.g. https://github.com/silverstripe/silverstripe-userforms/blob/5/code/Model/EditableFormField/EditableDateField.php#L65

**Comment by emteknetnz** [comment]
[Travis failures](https://github.com/silverstripe/silverstripe-spamprotection/pull/75/checks?check_run_id=1451737791) are unrelated to this PR so I'll merge as is.

**Comment by 3Dgoo** [comment]
Is it possible to do a new release with this change, please?

**Comment by emteknetnz** [comment]
@3Dgoo done https://github.com/silverstripe/silverstripe-spamprotection/releases/tag/3.0.3

**Comment by 3Dgoo** [comment]
Thank you

**Pull request merged**
