### PR TITLE
updating validateField method on EditableSpamProtectionField to use correct error message

### PR DESCRIPTION
**Pull request by timkung**

### CODE REVIEW

**Comment by chillu** [comment]
You've changed all the whitespace in this file, which makes it a bit hard to review. Is your IDE set up to perform that by default? For now, we can review it with the `w=0` flag in Github: https://github.com/silverstripe/silverstripe-spamprotection/pull/27/files?w=0

**Comment by timkung** [comment]
Yes sorry. I just changed it to meet PSR-2 with 4 spaces for indentation.

**Comment by dhensby** [comment]
> I just changed it to meet PSR-2 with 4 spaces for indentation.

We aren't PSR-2 compliant at the moment and the SS coding convention is tabs for now.

**Comment by timkung** [comment]
No worries, have reverted indentation back :)

**Comment by dhensby** [comment]
@timkung sorry to be a pain.. we now ARE PSR-2 please can you rebase and squash commits?

Maybe easier just to remove the last commit:

```sh
$ git checkout pulls/validate-field-fix
$ git reset --hard 935bcd0
$ git reset --hard HEAD^
$ git push -f origin pulls/validate-field-fix
```

**Comment by chillu** [comment]
@timkung I've fixed the formatting for you, and wrote some tests. Created a new PR for it: https://github.com/silverstripe/silverstripe-spamprotection/pull/44. Closing this one, can you please review my unit testing approach?

**Pull request closed without merging**
